version: "3"

services:
  server:
    image: movie-listing
    build:
      context: .
      target: development
    command: npm run dev
    environment:
      DATABASE_URL: "postgresql://johndoe:Password@123@db:5432/movies?schema=public"
      SECRET: "036accd2d3308f1589c426f4e71d1d7c9d618e2c48886edde71961a1dde6ffa63f4f566970b7acd6ea10925f4d3b2a8c5e75b77268c7553cd55ffd7ce1811fc4"
      LOG_LEVEL: debug
    ports:
      - 9000:9000
    volumes:
      - ./src:/home/app/src/
    depends_on:
      db:
        condition: service_started

  db:
    image: postgres:13
    ports:
      - "5532:5432"
    environment:
      POSTGRES_PASSWORD: Password@123
      POSTGRES_USER: johndoe
      POSTGRES_DB: movies
    volumes:
      - type: volume
        source: movies-db
        target: /var/lib/movies-db/data

volumes:
  movies-db:
